<<<<<<< HEAD
sudo: required
language: generic

=======
language: generic
sudo: required
>>>>>>> f78112efdf3878922cb69ed3c9dbee51a00bbbba
services:
  - docker

before_install:
<<<<<<< HEAD
  - docker build -t auggers/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true auggers/react-test npm test

after_success:
  - docker build -t auggers/multi-client ./client
  - docker build -t auggers/multi-nginx ./nginx
  - docker build -t auggers/multi-server ./server
  - docker build -t auggers/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push auggers/multi-client
  - docker push auggers/multi-nginx
  - docker push auggers/multi-server
  - docker push auggers/multi-worker
=======
  - docker build -t keithqui/docker_learning -f Dockerfile.dev .

script:
  - docker run -e CI=true keithqui/docker_learning npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-284712153045"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
>>>>>>> f78112efdf3878922cb69ed3c9dbee51a00bbbba
