language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t keithqui/docker_learning -f Dockerfile.dev .

script:
  - docker run -e CI=true keithqui/docker_learning npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-284712153045"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY